# Generated by Django 6.0.7 on 2026-08-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access_control", "0002_ticketqueueaccessgrant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffaccessprofile",
            name="all_ticket_queues",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Allow access to every ticket queue when the user also has the "
                    "required capability permission."
                ),
            ),
        ),
    ]
