# Generated by Django 5.2.5 on 2026-01-30 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Blog Categories",
            },
        ),
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="FAQCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "FAQ Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("challenge", models.TextField(help_text="Problem statement or challenge")),
                ("solution", models.TextField(help_text="How we solved it")),
                ("results", models.TextField(help_text="Outcome and results")),
                ("image", models.ImageField(blank=True, upload_to="portfolio/")),
                ("featured", models.BooleanField(default=False)),
                ("featured_image", models.ImageField(blank=True, upload_to="portfolio/featured/")),
                (
                    "technologies",
                    models.TextField(help_text="Comma-separated list of technologies"),
                ),
                ("project_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quote", models.TextField()),
                ("client_name", models.CharField(max_length=150)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("job_title", models.CharField(blank=True, max_length=150)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (5, "⭐⭐⭐⭐⭐"),
                            (4, "⭐⭐⭐⭐"),
                            (3, "⭐⭐⭐"),
                            (2, "⭐⭐"),
                            (1, "⭐"),
                        ],
                        default=5,
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="testimonials/")),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("excerpt", models.TextField(max_length=500)),
                ("content", models.TextField(help_text="Markdown content")),
                ("featured_image", models.ImageField(blank=True, upload_to="blog/")),
                ("author", models.CharField(default="ADB Software Solutions", max_length=100)),
                ("published", models.BooleanField(default=False)),
                ("featured", models.BooleanField(default=False)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("meta_keywords", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(related_name="posts", to="website.blogcategory"),
                ),
                ("tags", models.ManyToManyField(related_name="posts", to="website.blogtag")),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField(help_text="Markdown content")),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="website.faqcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
