#!/usr/bin/env bash
set -eu

version=0.10.0
machine="$(uname -m)"

case "$machine" in
	x86_64 | amd64)
		architecture=x86_64
		sha256=6c881ab0698e4e6ea235245f22832860544f17ba386442fe7e9d629f8cbedf87
		;;
	aarch64 | arm64)
		architecture=aarch64
		sha256=324a7e89de8fa2aed0d0c28f3dab59cf84c6d74264022c00c22af665ed1a09bb
		;;
	*)
		echo "Unsupported ShellCheck architecture: $machine" >&2
		exit 1
		;;
esac

tarball="shellcheck-v$version.linux.$architecture.tar.xz"

check_version() {
	out="$(shellcheck --version 2>/dev/null)" && [[ "$out" = *"
version: $version
"* ]]
}

if ! check_version; then
	tmpdir="$(mktemp -d)"
	trap 'rm -r "$tmpdir"' EXIT
	cd "$tmpdir"
	wget -nv "https://github.com/koalaman/shellcheck/releases/download/v$version/$tarball"
	sha256sum -c <<<"$sha256 $tarball"
	tar -xJf "$tarball" --no-same-owner --strip-components=1 -C /usr/local/bin "shellcheck-v$version/shellcheck"
	check_version
fi
