# Generated by Django 6.0 on 2026-08-28

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticketing", "0005_vendor_routing"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketqueue",
            name="first_response_sla_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional first-response target applied to tickets entering this queue.",
                null=True,
                validators=[MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="ticketqueue",
            name="resolution_sla_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional resolution target applied to tickets entering this queue.",
                null=True,
                validators=[MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="first_response_due_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="resolution_due_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
