"""Infrastructure model exports.

The original flat infrastructure records remain available while the structured
resource layer is introduced alongside them. They will be migrated onto the new
resource identities incrementally rather than rewritten in place.
"""

from .data_application_models import (
    ApplicationEnvironment,
    ApplicationProfile,
    ApplicationRepositoryLink,
    DatabaseInstance,
    LogicalDatabase,
    SourceRepository,
)
from .legacy_models import (
    API,
    Application,
    Bot,
    Database,
    Domain,
    EmailSystem,
    Licence,
    MobileApp,
    Server,
    SSLCertificate,
    Website,
    WebsiteTechStack,
)
from .legacy_resource_links import (
    APIResourceIdentity,
    ApplicationResourceIdentity,
    BotResourceIdentity,
    DatabaseResourceIdentity,
    DomainResourceIdentity,
    EmailSystemResourceIdentity,
    LicenceResourceIdentity,
    MobileAppResourceIdentity,
    ServerResourceIdentity,
    SSLCertificateResourceIdentity,
    WebsiteResourceIdentity,
)
from .operational_models import (
    BackupPlanProfile,
    BackupSource,
    ContainerService,
    ContainerStackProfile,
    HelmRelease,
    KubernetesClusterProfile,
    KubernetesIngress,
    KubernetesNamespaceProfile,
    KubernetesPersistentStorage,
    KubernetesService,
    KubernetesWorkloadProfile,
    ScheduledJobProfile,
    StorageProfile,
    SystemServiceProfile,
)
from .resource_models import (
    InfrastructureResource,
    InfrastructureTag,
    ProviderAccount,
    ResourceRelationship,
    ServiceProvider,
)
from .specialist_models import IPAddress, Network, NetworkInterface, ServerProfile, Subnet
from .web_domain_models import (
    DNSRecord,
    DNSZone,
    DomainProfile,
    TLSCertificate,
    TLSCertificateDomain,
    WebsiteEndpoint,
    WebsiteProfile,
)

__all__ = [
    "API",
    "APIResourceIdentity",
    "Application",
    "ApplicationEnvironment",
    "ApplicationProfile",
    "ApplicationRepositoryLink",
    "ApplicationResourceIdentity",
    "BackupPlanProfile",
    "BackupSource",
    "Bot",
    "BotResourceIdentity",
    "ContainerService",
    "ContainerStackProfile",
    "DNSRecord",
    "DNSZone",
    "Database",
    "DatabaseInstance",
    "DatabaseResourceIdentity",
    "Domain",
    "DomainProfile",
    "DomainResourceIdentity",
    "EmailSystem",
    "EmailSystemResourceIdentity",
    "HelmRelease",
    "IPAddress",
    "InfrastructureResource",
    "InfrastructureTag",
    "KubernetesClusterProfile",
    "KubernetesIngress",
    "KubernetesNamespaceProfile",
    "KubernetesPersistentStorage",
    "KubernetesService",
    "KubernetesWorkloadProfile",
    "Licence",
    "LicenceResourceIdentity",
    "LogicalDatabase",
    "MobileApp",
    "MobileAppResourceIdentity",
    "Network",
    "NetworkInterface",
    "ProviderAccount",
    "ResourceRelationship",
    "SSLCertificate",
    "SSLCertificateResourceIdentity",
    "ScheduledJobProfile",
    "Server",
    "ServerProfile",
    "ServerResourceIdentity",
    "ServiceProvider",
    "SourceRepository",
    "StorageProfile",
    "Subnet",
    "SystemServiceProfile",
    "TLSCertificate",
    "TLSCertificateDomain",
    "Website",
    "WebsiteEndpoint",
    "WebsiteProfile",
    "WebsiteResourceIdentity",
    "WebsiteTechStack",
]
