# Generated by Django 6.0 on 2026-08-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_dashboardpreference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="client_id",
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="resource_id",
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("task", "Task"),
                            ("ticket", "Ticket"),
                            ("credential", "Credential"),
                            ("monitoring", "Monitoring"),
                            ("security", "Security"),
                            ("calendar", "Calendar"),
                            ("general", "General"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=16,
                    ),
                ),
                ("source_key", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                ("href", models.CharField(blank=True, max_length=500)),
                ("client_id", models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ("resource_id", models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "resolved_at", "dismissed_at", "created_at"],
                        name="notification_user_state_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "source_key"),
                        name="unique_operational_notification_source",
                    )
                ],
            },
        ),
    ]
