# Generated by Django 5.2.5 on 2026-01-30 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="API",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "api_type",
                    models.CharField(
                        choices=[
                            ("rest", "REST"),
                            ("graphql", "GraphQL"),
                            ("webhook", "Webhook"),
                            ("rpc", "RPC"),
                            ("internal", "Internal"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("base_url", models.URLField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private_key", "Private (API Key)"),
                            ("private_session", "Private (Session)"),
                        ],
                        default="private_session",
                        max_length=50,
                    ),
                ),
                (
                    "authentication",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("api_key", "API Key"),
                            ("oauth", "OAuth"),
                            ("jwt", "JWT"),
                            ("session", "Session"),
                        ],
                        default="session",
                        max_length=50,
                    ),
                ),
                ("versioning_strategy", models.CharField(blank=True, max_length=100)),
                ("rate_limiting", models.TextField(blank=True)),
                ("documentation_url", models.URLField(blank=True)),
                ("github_repository", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitch", "Twitch"),
                            ("discord", "Discord"),
                            ("slack", "Slack"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "bot_type",
                    models.CharField(
                        choices=[
                            ("chat", "Chat Bot"),
                            ("moderation", "Moderation"),
                            ("automation", "Automation"),
                            ("integration", "Integration"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "runtime",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("nodejs", "Node.js"),
                            ("go", "Go"),
                            ("rust", "Rust"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("hosting_location", models.CharField(blank=True, max_length=200)),
                (
                    "permissions",
                    models.TextField(blank=True, help_text="List of permissions/scopes"),
                ),
                ("github_repository", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("domain_name", models.CharField(max_length=200, unique=True)),
                (
                    "registrar",
                    models.CharField(
                        choices=[
                            ("godaddy", "GoDaddy"),
                            ("namecheap", "Namecheap"),
                            ("route53", "Route 53"),
                            ("cloudflare", "Cloudflare"),
                            ("google_domains", "Google Domains"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("expiry_date", models.DateField()),
                ("auto_renew", models.BooleanField(default=True)),
                ("nameservers", models.TextField(blank=True, help_text="Comma-separated list")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["domain_name"],
            },
        ),
        migrations.CreateModel(
            name="EmailSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("exchange", "Microsoft Exchange"),
                            ("microsoft_365", "Microsoft 365"),
                            ("google_workspace", "Google Workspace"),
                            ("self_hosted", "Self-Hosted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("admin_portal_url", models.URLField(blank=True)),
                ("domains", models.TextField(blank=True, help_text="Comma-separated list")),
                ("spf_status", models.CharField(blank=True, max_length=50)),
                ("dkim_status", models.CharField(blank=True, max_length=50)),
                ("dmarc_status", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MobileApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("both", "Both (Cross-platform)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("swift", "Swift"),
                            ("kotlin", "Kotlin"),
                            ("react_native", "React Native"),
                            ("flutter", "Flutter"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "bundle_id",
                    models.CharField(
                        blank=True,
                        help_text="Android package name or iOS bundle ID",
                        max_length=200,
                    ),
                ),
                ("current_version", models.CharField(blank=True, max_length=50)),
                (
                    "release_status",
                    models.CharField(
                        choices=[
                            ("development", "Development"),
                            ("testing", "Testing"),
                            ("live", "Live"),
                            ("archived", "Archived"),
                        ],
                        default="development",
                        max_length=50,
                    ),
                ),
                ("app_store_link", models.URLField(blank=True)),
                ("play_store_link", models.URLField(blank=True)),
                ("backend_api", models.URLField(blank=True)),
                ("github_repository", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hostname", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("web", "Web Server"),
                            ("database", "Database"),
                            ("management", "Management"),
                            ("ci", "CI/CD"),
                            ("backup", "Backup"),
                            ("cache", "Cache"),
                            ("other", "Other"),
                        ],
                        default="web",
                        max_length=50,
                    ),
                ),
                ("public_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("private_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("do", "DigitalOcean"),
                            ("aws", "AWS"),
                            ("linode", "Linode"),
                            ("vultr", "Vultr"),
                            ("google_cloud", "Google Cloud"),
                            ("azure", "Azure"),
                            ("on_premise", "On-Premise"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "os",
                    models.CharField(
                        choices=[
                            ("ubuntu_20", "Ubuntu 20.04"),
                            ("ubuntu_22", "Ubuntu 22.04"),
                            ("ubuntu_24", "Ubuntu 24.04"),
                            ("debian_11", "Debian 11"),
                            ("debian_12", "Debian 12"),
                            ("centos_7", "CentOS 7"),
                            ("centos_8", "CentOS 8"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cpu", models.CharField(blank=True, max_length=100)),
                ("ram_gb", models.IntegerField(blank=True, null=True)),
                ("disk_gb", models.IntegerField(blank=True, null=True)),
                (
                    "virtualization_type",
                    models.CharField(
                        choices=[
                            ("bare_metal", "Bare Metal"),
                            ("vm", "Virtual Machine"),
                            ("container_host", "Container Host"),
                        ],
                        default="vm",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["hostname"],
            },
        ),
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("mysql", "MySQL"),
                            ("postgres", "PostgreSQL"),
                            ("mongodb", "MongoDB"),
                            ("redis", "Redis"),
                            ("mariadb", "MariaDB"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("self_hosted", "Self-Hosted"),
                            ("do", "DigitalOcean"),
                            ("aws_rds", "AWS RDS"),
                            ("aws_dynamodb", "AWS DynamoDB"),
                            ("google_cloud", "Google Cloud"),
                            ("azure", "Azure"),
                            ("heroku", "Heroku"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=50)),
                ("backup_strategy", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="infrastructure.server",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Databases",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SSLCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("letsencrypt", "Let's Encrypt"),
                            ("cloudflare", "Cloudflare"),
                            ("comodo", "Comodo"),
                            ("sectigo", "Sectigo"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cert_type", models.CharField(blank=True, max_length=100)),
                ("expiry_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssl_certificates",
                        to="infrastructure.domain",
                    ),
                ),
            ],
            options={
                "ordering": ["domain"],
            },
        ),
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("primary_url", models.URLField()),
                (
                    "environment_type",
                    models.CharField(
                        choices=[
                            ("production", "Production"),
                            ("staging", "Staging"),
                            ("development", "Development"),
                            ("testing", "Testing"),
                        ],
                        default="production",
                        max_length=50,
                    ),
                ),
                ("admin_url", models.URLField(blank=True)),
                ("github_repository", models.URLField(blank=True)),
                ("has_cdn", models.BooleanField(default=False)),
                ("cdn_provider", models.CharField(blank=True, max_length=100)),
                (
                    "cache_layer",
                    models.CharField(blank=True, help_text="e.g., Varnish, Redis", max_length=100),
                ),
                ("aliases", models.TextField(blank=True, help_text="Comma-separated list")),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "database",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="infrastructure.database",
                    ),
                ),
                (
                    "servers",
                    models.ManyToManyField(related_name="websites", to="infrastructure.server"),
                ),
                (
                    "staging_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="infrastructure.website",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Licence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "licence_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription"),
                            ("perpetual", "Perpetual"),
                            ("trial", "Trial"),
                        ],
                        max_length=50,
                    ),
                ),
                ("vendor", models.CharField(max_length=200)),
                ("renewal_date", models.DateField()),
                (
                    "renewal_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("auto_renew", models.BooleanField(default=True)),
                ("portal_url", models.URLField(blank=True)),
                ("licence_key", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "websites",
                    models.ManyToManyField(
                        blank=True, related_name="licences", to="infrastructure.website"
                    ),
                ),
            ],
            options={
                "ordering": ["-renewal_date"],
            },
        ),
        migrations.AddField(
            model_name="domain",
            name="websites",
            field=models.ManyToManyField(
                blank=True, related_name="domains", to="infrastructure.website"
            ),
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "app_type",
                    models.CharField(
                        choices=[
                            ("web_app", "Web Application"),
                            ("saas", "SaaS"),
                            ("bot", "Bot"),
                            ("mobile", "Mobile App"),
                            ("hybrid", "Hybrid"),
                            ("api", "API"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("maintenance", "Maintenance"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "databases",
                    models.ManyToManyField(
                        blank=True, related_name="applications", to="infrastructure.database"
                    ),
                ),
                (
                    "domains",
                    models.ManyToManyField(
                        blank=True, related_name="applications", to="infrastructure.domain"
                    ),
                ),
                (
                    "licences",
                    models.ManyToManyField(
                        blank=True, related_name="applications", to="infrastructure.licence"
                    ),
                ),
                (
                    "servers",
                    models.ManyToManyField(
                        blank=True, related_name="applications", to="infrastructure.server"
                    ),
                ),
                (
                    "websites",
                    models.ManyToManyField(
                        blank=True, related_name="applications", to="infrastructure.website"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteTechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "technology",
                    models.CharField(help_text="e.g., Next.js, Django, PostgreSQL", max_length=200),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend"),
                            ("backend", "Backend"),
                            ("database", "Database"),
                            ("cms", "CMS"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=50)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_stack",
                        to="infrastructure.website",
                    ),
                ),
            ],
            options={
                "unique_together": {("website", "technology")},
            },
        ),
    ]
