# Generated by Django 6.0.8 on 2026-08-26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0004_compute_network_specialists"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("web_app", "Web application"),
                            ("saas", "SaaS"),
                            ("api", "API"),
                            ("service", "Service"),
                            ("worker", "Worker"),
                            ("bot", "Bot"),
                            ("mobile", "Mobile app"),
                            ("hybrid", "Hybrid"),
                            ("integration", "Integration"),
                            ("other", "Other"),
                        ],
                        default="web_app",
                        max_length=30,
                    ),
                ),
                ("owner_team", models.CharField(blank=True, max_length=200)),
                ("primary_language", models.CharField(blank=True, max_length=100)),
                ("framework", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_profile",
                        to="infrastructure.infrastructureresource",
                    ),
                ),
            ],
            options={"ordering": ["resource__name", "id"]},
        ),
        migrations.CreateModel(
            name="DatabaseInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("postgresql", "PostgreSQL"),
                            ("mysql", "MySQL"),
                            ("mariadb", "MariaDB"),
                            ("mongodb", "MongoDB"),
                            ("redis", "Redis"),
                            ("sql_server", "SQL Server"),
                            ("oracle", "Oracle"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("engine_version", models.CharField(blank=True, max_length=100)),
                (
                    "hosting_type",
                    models.CharField(
                        choices=[
                            ("managed", "Managed service"),
                            ("self_hosted", "Self-hosted"),
                            ("container", "Container"),
                            ("appliance", "Appliance"),
                            ("other", "Other"),
                        ],
                        default="managed",
                        max_length=30,
                    ),
                ),
                ("provider_resource_id", models.CharField(blank=True, max_length=200)),
                ("endpoint", models.CharField(blank=True, max_length=253)),
                (
                    "port",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=100)),
                ("zone", models.CharField(blank=True, max_length=100)),
                (
                    "tls_mode",
                    models.CharField(
                        choices=[
                            ("required", "Required"),
                            ("preferred", "Preferred"),
                            ("disabled", "Disabled"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("high_availability", models.BooleanField(blank=True, null=True)),
                ("replica_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("backup_enabled", models.BooleanField(blank=True, null=True)),
                ("maintenance_window", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="database_instances",
                        to="infrastructure.provideraccount",
                    ),
                ),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="database_instance",
                        to="infrastructure.infrastructureresource",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="database_instances",
                        to="infrastructure.serverprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["resource__name", "id"],
                "indexes": [
                    models.Index(
                        fields=["engine", "hosting_type"], name="infra_db_engine_host_idx"
                    ),
                    models.Index(
                        fields=["provider_account", "region"], name="infra_db_provider_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("web_url", models.URLField(blank=True)),
                ("clone_url", models.CharField(blank=True, max_length=500)),
                ("provider_repository_id", models.CharField(blank=True, max_length=200)),
                ("owner_name", models.CharField(blank=True, max_length=200)),
                ("repository_name", models.CharField(max_length=200)),
                ("default_branch", models.CharField(blank=True, max_length=200)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("internal", "Internal"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("is_fork", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_repositories",
                        to="infrastructure.provideraccount",
                    ),
                ),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_repository",
                        to="infrastructure.infrastructureresource",
                    ),
                ),
            ],
            options={
                "ordering": ["owner_name", "repository_name", "id"],
                "indexes": [
                    models.Index(
                        fields=["provider_account", "owner_name", "repository_name"],
                        name="infra_repo_provider_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ApplicationEnvironment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "deployment_type",
                    models.CharField(
                        choices=[
                            ("server", "Server"),
                            ("paas", "PaaS"),
                            ("container", "Container"),
                            ("kubernetes", "Kubernetes"),
                            ("serverless", "Serverless"),
                            ("static", "Static"),
                            ("other", "Other"),
                        ],
                        default="server",
                        max_length=30,
                    ),
                ),
                ("provider_resource_id", models.CharField(blank=True, max_length=200)),
                ("runtime", models.CharField(blank=True, max_length=100)),
                ("runtime_version", models.CharField(blank=True, max_length=100)),
                ("release_version", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("branch_or_ref", models.CharField(blank=True, max_length=200)),
                ("automatic_deployments", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environments",
                        to="infrastructure.applicationprofile",
                    ),
                ),
                (
                    "provider_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_environments",
                        to="infrastructure.provideraccount",
                    ),
                ),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_environment",
                        to="infrastructure.infrastructureresource",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_environments",
                        to="infrastructure.serverprofile",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "application__resource__name",
                    "resource__environment",
                    "resource__name",
                    "id",
                ]
            },
        ),
        migrations.CreateModel(
            name="LogicalDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("database_name", models.CharField(max_length=200)),
                ("purpose", models.CharField(blank=True, max_length=255)),
                ("default_schema", models.CharField(blank=True, max_length=100)),
                ("charset", models.CharField(blank=True, max_length=100)),
                ("collation", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logical_databases",
                        to="infrastructure.databaseinstance",
                    ),
                ),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logical_database",
                        to="infrastructure.infrastructureresource",
                    ),
                ),
            ],
            options={
                "ordering": ["instance__resource__name", "database_name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("instance", "database_name"),
                        name="unique_logical_database_on_instance",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ApplicationRepositoryLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("backend", "Backend"),
                            ("frontend", "Frontend"),
                            ("infrastructure", "Infrastructure"),
                            ("mobile", "Mobile"),
                            ("documentation", "Documentation"),
                            ("other", "Other"),
                        ],
                        default="primary",
                        max_length=30,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text="Optional monorepo path or component directory.",
                        max_length=500,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repository_links",
                        to="infrastructure.applicationprofile",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_links",
                        to="infrastructure.sourcerepository",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "application__resource__name",
                    "role",
                    "repository__resource__name",
                    "id",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "repository", "role", "path"),
                        name="unique_application_repository_role_path",
                    )
                ],
            },
        ),
    ]
