# Generated by Django 6.0.8 on 2026-08-26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0005_data_application_specialists"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain_name", models.CharField(max_length=253, unique=True)),
                ("provider_domain_id", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("transferring", "Transferring"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("registered_on", models.DateField(blank=True, null=True)),
                ("expires_on", models.DateField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(blank=True, null=True)),
                ("transfer_lock_enabled", models.BooleanField(blank=True, null=True)),
                ("privacy_enabled", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registrar_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_domains",
                        to="infrastructure.provideraccount",
                    ),
                ),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_profile",
                        to="infrastructure.infrastructureresource",
                    ),
                ),
            ],
            options={"ordering": ["domain_name", "id"]},
        ),
        migrations.CreateModel(
            name="TLSCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("managed", "Managed"),
                            ("acme", "ACME"),
                            ("imported", "Imported"),
                            ("self_signed", "Self-signed"),
                            ("other", "Other"),
                        ],
                        default="managed",
                        max_length=20,
                    ),
                ),
                ("issuer", models.CharField(blank=True, max_length=255)),
                ("subject_common_name", models.CharField(blank=True, max_length=253)),
                ("provider_certificate_id", models.CharField(blank=True, max_length=200)),
                ("serial_number", models.CharField(blank=True, max_length=200)),
                ("fingerprint_sha256", models.CharField(blank=True, max_length=95)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tls_certificates",
                        to="infrastructure.provideraccount",
                    ),
                ),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tls_certificate",
                        to="infrastructure.infrastructureresource",
                    ),
                ),
            ],
            options={
                "ordering": ["resource__name", "id"],
                "indexes": [models.Index(fields=["expires_at"], name="infra_tls_expiry_idx")],
            },
        ),
        migrations.CreateModel(
            name="WebsiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "website_type",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing site"),
                            ("web_app", "Web application"),
                            ("ecommerce", "E-commerce"),
                            ("cms", "CMS site"),
                            ("portal", "Portal"),
                            ("static", "Static site"),
                            ("other", "Other"),
                        ],
                        default="web_app",
                        max_length=30,
                    ),
                ),
                ("admin_url", models.URLField(blank=True)),
                ("cms", models.CharField(blank=True, max_length=100)),
                ("cms_version", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cdn_provider_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cdn_websites",
                        to="infrastructure.provideraccount",
                    ),
                ),
                (
                    "hosting_provider_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_websites",
                        to="infrastructure.provideraccount",
                    ),
                ),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_profile",
                        to="infrastructure.infrastructureresource",
                    ),
                ),
                (
                    "waf_provider_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waf_websites",
                        to="infrastructure.provideraccount",
                    ),
                ),
            ],
            options={"ordering": ["resource__name", "id"]},
        ),
        migrations.CreateModel(
            name="DNSZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone_name", models.CharField(max_length=253)),
                ("provider_zone_id", models.CharField(blank=True, max_length=200)),
                ("dnssec_enabled", models.BooleanField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dns_zones",
                        to="infrastructure.domainprofile",
                    ),
                ),
                (
                    "provider_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dns_zones",
                        to="infrastructure.provideraccount",
                    ),
                ),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dns_zone",
                        to="infrastructure.infrastructureresource",
                    ),
                ),
            ],
            options={
                "ordering": ["zone_name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("domain", "zone_name"),
                        name="unique_dns_zone_name_per_domain",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TLSCertificateDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_links",
                        to="infrastructure.tlscertificate",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tls_certificate_links",
                        to="infrastructure.domainprofile",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "certificate__resource__name",
                    "domain__domain_name",
                    "id",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("certificate", "domain"),
                        name="unique_tls_certificate_domain",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WebsiteEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("alias", "Alias"),
                            ("staging", "Staging"),
                            ("development", "Development"),
                            ("admin", "Admin"),
                            ("api", "API"),
                            ("health", "Health"),
                            ("other", "Other"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("redirects_to", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application_environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="website_endpoints",
                        to="infrastructure.applicationenvironment",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="website_endpoints",
                        to="infrastructure.domainprofile",
                    ),
                ),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_endpoint",
                        to="infrastructure.infrastructureresource",
                    ),
                ),
                (
                    "tls_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="website_endpoints",
                        to="infrastructure.tlscertificate",
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="infrastructure.websiteprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["website__resource__name", "role", "url", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("website", "url"),
                        name="unique_website_endpoint_url",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("website",),
                        name="unique_primary_website_endpoint",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DNSRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=253)),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("AAAA", "AAAA"),
                            ("CNAME", "CNAME"),
                            ("MX", "MX"),
                            ("TXT", "TXT"),
                            ("NS", "NS"),
                            ("SRV", "SRV"),
                            ("CAA", "CAA"),
                            ("PTR", "PTR"),
                            ("ALIAS", "ALIAS"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.TextField()),
                (
                    "ttl",
                    models.PositiveIntegerField(
                        default=300,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("priority", models.PositiveIntegerField(blank=True, null=True)),
                ("weight", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "port",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                ("proxied", models.BooleanField(blank=True, null=True)),
                ("provider_record_id", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="infrastructure.dnszone",
                    ),
                ),
            ],
            options={
                "ordering": ["zone__zone_name", "name", "record_type", "id"],
                "indexes": [
                    models.Index(
                        fields=["zone", "name", "record_type"],
                        name="infra_dns_record_idx",
                    )
                ],
            },
        ),
    ]
