# Generated by Django 6.0.8 on 2026-08-25 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credentials", "0005_typed_credential_vault"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedcredential",
            name="credential_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credentials",
                to="credentials.credentialtype",
            ),
        ),
    ]
