# Generated by Django 6.0 on 2026-08-28

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credentials", "0006_alter_storedcredential_credential_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedcredential",
            name="rotation_interval_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional maximum age before this credential should be rotated.",
                null=True,
                validators=[MinValueValidator(1)],
            ),
        ),
    ]
